Edit Jenkinsfile-CICD

diff --git a/Jenkinsfile-CICD b/Jenkinsfile-CICD
--- a/Jenkinsfile-CICD
+++ b/Jenkinsfile-CICD
@@ -1,97 +1,129 @@
 pipeline {
-  agent { label 'build' }
-   environment { 
-        registry = "adamtravis/democicd" 
-        registryCredential = 'dockerhub' 
-   }
-   parameters {
-    password(name: 'PASSWD', defaultValue: '', description: 'Please Enter your Gitlab password')
-   }
+    agent any
 
-  stages {
-   stage('Stage I: Build') {
-      steps {
-        git branch: 'main', credentialsId: 'GitlabCred', url: 'https://gitlab.com/learndevopseasy/devsecops/springboot-build-pipeline.git'
-        echo "Building Jar Component ..."
-        sh "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64; mvn clean package "
-      }
+    environment { 
+        registry = "dark5980/democicd" 
+        registryCredential = 'dockercri' 
     }
 
-   stage('Stage II: Code Coverage ') {
-      steps {
-	    echo "Running Code Coverage ..."
-        sh "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64; mvn jacoco:report"
-      }
+    parameters {
+        password(name: 'PASSWD', defaultValue: '', description: 'Please Enter your Gitlab password')
+        string(name: 'IMAGETAG', defaultValue: '1', description: 'Please Enter the Image Tag to Deploy?')
     }
 
-   stage('Stage III: SCA') {
-      steps { 
-        echo "Running Software Composition Analysis using OWASP Dependency-Check ..."
-        sh "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64; mvn org.owasp:dependency-check-maven:check"
-      }
-    }
-
-   stage('Stage IV: SAST') {
-      steps { 
-        echo "Running Static application security testing using SonarQube Scanner ..."
-        withSonarQubeEnv('mysonarqube') {
-            sh 'mvn sonar:sonar -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml -Dsonar.dependencyCheck.jsonReportPath=target/dependency-check-report.json -Dsonar.dependencyCheck.htmlReportPath=target/dependency-check-report.html -Dsonar.projectName=wezvatech'
-       }
-      }
-    }
-
-   stage('Stage V: QualityGates') {
-      steps { 
-        echo "Running Quality Gates to verify the code quality"
-        script {
-          timeout(time: 1, unit: 'MINUTES') {
-            def qg = waitForQualityGate()
-            if (qg.status != 'OK') {
-              error "Pipeline aborted due to quality gate failure: ${qg.status}"
-            }
-           }
-        }
-      }
-    }
-   
-   stage('Stage VI: Build Image') {
-      steps { 
-        echo "Build Docker Image"
-        script {
-               docker.withRegistry( '', registryCredential ) { 
-                 myImage = docker.build registry + ":$BUILD_NUMBER" 
-                 myImage.push()
+    stages {
+        stage('Build') {
+            steps {
+                echo "Building Jar Component ..."
+                dir('/var/lib/jenkins/workspace/devops') {
+                    sh "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64; mvn clean package"
                 }
+            }
         }
-      }
-    }
-        
-   stage('Stage VII: Scan Image ') {
-      steps { 
-        echo "Scanning Image for Vulnerabilities"
-        sh "trivy image --scanners vuln --offline-scan adamtravis/democicd:$BUILD_NUMBER > trivyresults.txt"
-        }
-    }
-          
-   stage('Stage VIII: Smoke Test ') {
-      steps { 
-        echo "Smoke Test the Image"
-        sh "docker run -d --name smokerun -p 8080:8080 adamtravis/democicd:$BUILD_NUMBER"
-        sh "sleep 90; ./check.sh"
-        sh "docker rm --force smokerun"
-        }
-    }
 
-   stage('Stage IX: Trigger Deployment'){
-      steps { 
-       script {
-        TAG = "$BUILD_NUMBER"
-         echo "Trigger CD Pipeline"
-          build wait: false, job: 'springboot-cd-pipeline', parameters: [password(name: 'PASSWD', description: 'Please Enter your Gitlab password', value: params.PASSWD),string(name: 'IMAGETAG', value: TAG)]
-       }
-      }
+        stage('Code Coverage') {
+            steps {
+                echo "Running Code Coverage ..."
+                dir('/var/lib/jenkins/workspace/devops') {
+                    sh "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64; mvn jacoco:report"
+                }
+            }
+        }
+
+        stage('SAST') {
+            steps { 
+                echo "Running Static Application Security Testing using SonarQube Scanner ..."
+                dir('/var/lib/jenkins/workspace/devops') {
+                    withSonarQubeEnv('sonar') {
+                        sh 'mvn sonar:sonar -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml -Dsonar.projectName=wezvatech'
+                    }
+                }
+            }
+        }
+
+        stage('Quality Gates') {
+            steps { 
+                echo "Running Quality Gates to verify the code quality"
+                dir('/var/lib/jenkins/workspace/devops') {
+                    script {
+                        timeout(time: 1, unit: 'MINUTES') {
+                            def qg = waitForQualityGate()
+                            if (qg.status != 'OK') {
+                                error "Pipeline aborted due to quality gate failure: ${qg.status}"
+                            }
+                        }
+                    }
+                }
+            }
+        }
+
+        stage('Build Docker Image') {
+            steps { 
+                echo "Build Docker Image"
+                dir('/var/lib/jenkins/workspace/devops') {
+                    script {
+                        docker.withRegistry('', registryCredential) { 
+                            def myImage = docker.build(registry)
+                            myImage.push()
+                        }
+                    }
+                }
+            }
+        }
+
+        stage('Scan Docker Image') {
+            steps { 
+                echo "Scanning Image for Vulnerabilities"
+                dir('/var/lib/jenkins/workspace/devops') {
+                    sh "trivy image --scanners vuln --offline-scan ${registry}:latest > trivyresults.txt"
+                }
+            }
+        }
+
+        stage('Smoke Test') {
+            steps { 
+                echo "Smoke Test the Image"
+                dir('/var/lib/jenkins/workspace/devops') {
+                    sh "docker run -d --name smokerun10 -p 9091:9091 ${registry}:latest"
+                    sh "sleep 90; ./check.sh"
+                    sh "docker rm --force smokerun10"
+                }
+            }
+        }
+
+        stage('Trigger CD Pipeline') {
+            steps { 
+                script {
+                    TAG = "${BUILD_NUMBER}"
+                    echo "Triggering CD Pipeline"
+                    build wait: false, job: 'devops1', parameters: [
+                        password(name: 'PASSWD', description: 'Please Enter your Gitlab password', value: params.PASSWD),
+                        string(name: 'IMAGETAG', value: TAG)
+                    ]
+                }
+            }
+        }
+
+        stage('CD Deployment') {
+            steps {
+                echo "Running CD Deployment..."
+                git branch: 'main', credentialsId: 'GitlabCred', url: 'https://gitlab.com/udaykumar5980/spingboot-cd-pipeline.git'
+                dir("/var/lib/jenkins/workspace/devops/kubernetes") {
+                    sh "sed -i 's|image: dark5980.*|image: dark5980/demo:${BUILD_NUMBER}|g' deployment.yml"
+                }
+                sh """
+                    git config user.email "udaykumar5980@example.com"
+                    git config user.name "udaykumar5980"
+                """
+                sh """
+                    if ! git diff --quiet; then
+                        git commit -am "New deployment for Build ${BUILD_NUMBER}"
+                        git push https://udaykumar5980:${params.PASSWD}@gitlab.com/udaykumar5980/spingboot-cd-pipeline.git
+                    else
+                        echo "No changes to commit"
+                    fi
+                """
+            }
+        }
     }
-   
-  }
 }
-
